name: CI/CD Deploy Technologyline-ecommerce-admin

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Desplegar vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/repositories/technologyline_admin
            git pull origin main
            npm install 
            npm run build
            rm -rf /home/technologyline/public_html/admin/page/assets/*
            rm -rf /home/technologyline/public_html/admin/page/index.html
            cp -r dist/* /home/technologyline/public_html/admin/page/
